name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npx -c 'tsc -p .'

      - name: Lint
        run: npx -c 'eslint .'

      - name: Test
        run: npx -c 'jest --ci'
