name: CI

on: push

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: npm ci --ignore-scripts
      - run: npx eslint .

  TypeScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: npm ci --ignore-scripts
      - run: npx tsc -p .

  Cypress:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - if: always()
        uses: actions/upload-artifact@v2.1.4
        with:
          name: cypress
          path: |
            cypress/screenshots/
            cypress/videos/
          if-no-files-found: ignore

  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
