name: CI

on: push

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: yarn install --immutable
      - run: yarn eslint .

  TypeScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: yarn install --immutable
      - run: yarn tsc -p .

  Cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: yarn install --immutable
      - uses: actions/cache@v2.1.1
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - uses: cypress-io/github-action@v2
        with:
          install: false
          build: yarn build
          start: yarn start
      - if: always()
        uses: actions/upload-artifact@v2.1.4
        with:
          name: cypress
          path: |
            cypress/screenshots/
            cypress/videos/
          if-no-files-found: ignore

  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: yarn install --immutable
      - uses: actions/cache@v2.1.1
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn build
      - run: yarn dlx -q -p @lhci/cli lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
